### ISSUE TITLE
sample is malicious or benign?

### ISSUE THREAD

**Issue by kylin-zhou** [packing-box/dataset-packed-elf#2]
Very great project ! I have some ploblem:
- All not-packed data are benign?
- All packed data is based on unpacked data, just using a different packer. That is, they are essentially benign.
- Anoather project dataset-packed-pe is the same?
Thanks.

**Comment by dhondta** [comment]
Hi @Aida-yy , thank you !
Answers to your questions :
* Yes, every sample from the [`not-packed`](https://github.com/packing-box/dataset-packed-elf/tree/master/not-packed) folder is cleanware coming from a fresh installation of Ubuntu 20.04 and its `/usr/bin` folder. In order to clarify this, I refined the README.
* Yes, therefore the packed samples are also cleanware.
* Yes, [`dataset-packed-pe`](https://github.com/packing-box/dataset-packed-pe) is built based on the same principle, using cleanware from a fresh Windows installation.

**Comment by kylin-zhou** [comment]
Thank you !
